/**
 * Small icon set used across the dashboard, wrapping lucide-react with the
 * project's `.ic` class so sizing/stroke match the design system.
 */
import {
  Home,
  ListChecks,
  Sparkles,
  SlidersHorizontal,
  Settings,
  Download,
  Code2,
  Bell,
  ChevronDown,
  Check,
  X,
  Eye,
  Clock,
  Ban,
  Zap,
  TriangleAlert,
  MessageSquare,
  Search,
  RotateCcw,
  Flag,
  Undo2,
  Send,
  Cpu,
  Globe,
  KeyRound,
  Info,
  Trash2,
  Twitch,
  LogOut,
  type LucideIcon,
} from 'lucide-react';

export type { LucideIcon };

export const Icons = {
  home: Home,
  moderation: ListChecks,
  sparkles: Sparkles,
  filters: SlidersHorizontal,
  settings: Settings,
  download: Download,
  code: Code2,
  bell: Bell,
  chevron: ChevronDown,
  check: Check,
  x: X,
  eye: Eye,
  clock: Clock,
  ban: Ban,
  bolt: Zap,
  alert: TriangleAlert,
  message: MessageSquare,
  search: Search,
  refresh: RotateCcw,
  flag: Flag,
  undo: Undo2,
  send: Send,
  cpu: Cpu,
  globe: Globe,
  key: KeyRound,
  info: Info,
  trash: Trash2,
  twitch: Twitch,
  logout: LogOut,
} satisfies Record<string, LucideIcon>;
