import {
  Home,
  Sparkles,
  Terminal,
  Settings,
  ShieldCheck,
  Shield,
  Twitch,
  Zap,
  Clock,
  Check,
  X,
  Eye,
  Ban,
  TriangleAlert,
  Send,
  Undo2,
  Minus,
  Square,
  ExternalLink,
  RotateCcw,
  Info,
  SlidersHorizontal,
  Wrench,
  Search,
  Download,
  Trash2,
  type LucideIcon,
} from 'lucide-react';

export const Icons = {
  home: Home,
  sparkles: Sparkles,
  terminal: Terminal,
  settings: Settings,
  shieldCheck: ShieldCheck,
  shield: Shield,
  twitch: Twitch,
  bolt: Zap,
  clock: Clock,
  check: Check,
  x: X,
  eye: Eye,
  ban: Ban,
  alert: TriangleAlert,
  send: Send,
  undo: Undo2,
  minus: Minus,
  square: Square,
  external: ExternalLink,
  refresh: RotateCcw,
  info: Info,
  sliders: SlidersHorizontal,
  wrench: Wrench,
  search: Search,
  download: Download,
  trash: Trash2,
} satisfies Record<string, LucideIcon>;
